name: DioneSMP
version: 1.0.0
main: com.dione.main.Main
description: Plugin Principal DioneSMP
author: Dione
api-version: '1.20.6'
depend:
  - Vault
  - Essentials
commands:
  lojaminer:
    description: Este comando abre a janela da Loja Mineiro para um jogador
    usage: /lojaminer <jogador>
    permission: dionesmp.lojaminer
  lojafarmer:
    description: Este comando abre a janela da Loja Fazendeiro para um jogador
    usage: /lojafarmer <jogador>
    permission: dionesmp.lojafarmer
  lojasmith:
    description: Este comando abre a janela da Loja Ferreiro para um jogador
    usage: /lojasmith <jogador>
    permission: dionesmp.lojasmith
  lojaspawner:
    description: Este comando abre a janela da Loja Spawner para um jogador
    usage: /lojaspawner <jogador>
    permission: dionesmp.lojaspawner
  lojaweapon:
    description: Este comando abre a janela da Loja Spawner para um jogador
    usage: /lojaweapon <jogador>
    permission: dionesmp.lojaweapon
  lojawitch:
    description: Este comando abre a janela da Loja Witch para um jogador
    usage: /lojawitch <jogador>
    permission: dionesmp.lojawitch
  lojabuilder:
    description: Este comando abre a janela da Loja Builder para um jogador
    usage: /lojabuilder <jogador>
    permission: dionesmp.lojabuilder
  giveminion:
    description: Da um minion de um tipo
    usage: /giveminion <type>
    permission: dionesmp.giveminion